name: Release
on:
  push:
    branches:
      - main

jobs:
  build:
    permissions: write-all
    name: Release
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
      - name: Release
        uses: justincy/github-action-npm-release@2.0.1
        id: release
      - name: Print release output
        if: ${{ steps.release.outputs.released == 'true' }}
        run: echo Release ID ${{ steps.release.outputs.release_id }}